// ============================================
//   CODEFLOW - TRANSPILER  (AST → Python)
//   Matches the exact node schema produced
//   by app.js v05.1
//
//   Node types (lowercase, as app.js emits):
//     show, read, assign, if, while, for,
//     loop, break, function_call, empty
//
//   Function definitions live in
//   FunctionRegistry, not in the main AST —
//   they are passed separately via `functions`.
// ============================================

'use strict';

const INDENT = '    '; // 4-space Python indent

// ── Public entry point ────────────────────────────────────────────────────
// nodes     : ASTManager.root.children  (cleaned by ExportadorAST)
// variables : VariableRegistry.getAll()
// functions : FunctionRegistry.getAll()
function transpile(nodes, variables = [], functions = []) {
  const varMap  = buildVarMap(variables);
  const funcMap = buildFuncMap(functions);
  const ctx     = { varMap, funcMap, indent: 0 };

  const parts = [
    buildHeader(),
    buildVarDeclarations(variables),
    buildFunctionDefs(functions, ctx),
    walkNodes(nodes, ctx)
  ];

  return parts.filter(Boolean).join('\n');
}

// ── Lookup maps ───────────────────────────────────────────────────────────
function buildVarMap(variables) {
  const map = {};
  variables.forEach(v => { map[v.id] = v; });
  return map;
}

function buildFuncMap(functions) {
  const map = {};
  functions.forEach(f => { map[f.id] = f; });
  return map;
}

// ── File header ───────────────────────────────────────────────────────────
function buildHeader() {
  const now = new Date().toISOString().replace('T', ' ').slice(0, 19);
  return [
    `# Generated by CodeFlow  —  ${now}`,
    `# -----------------------------------------------`,
    ``
  ].join('\n');
}

// ── Variable declarations ─────────────────────────────────────────────────
// Emits:  nombre = 0  /  texto = ""  /  activo = False  /  lista = []
function buildVarDeclarations(variables) {
  if (!variables.length) return '';
  return variables
    .map(v => `${sanitizeName(v.name)} = ${pyDefaultValue(v.type, v.value)}`)
    .join('\n') + '\n';
}

// ── Function definitions ──────────────────────────────────────────────────
// Functions in CodeFlow have: name, argVarId (optional), returnVarId (optional),
// children[] (their body AST nodes).
function buildFunctionDefs(functions, ctx) {
  if (!functions.length) return '';

  return functions.map(f => {
    const name   = sanitizeName(f.name);
    const param  = f.argVarId ? resolveName(f.argVarId, ctx) : '';
    const body   = walkNodes(f.children || [], { ...ctx, indent: 1 });
    const ret    = f.returnVarId ? `${INDENT}return ${resolveName(f.returnVarId, ctx)}` : '';

    const bodyLines = [body, ret].filter(Boolean).join('\n') || `${INDENT}pass`;
    return `def ${name}(${param}):\n${bodyLines}`;
  }).join('\n\n') + '\n';
}

// ── Walk a list of nodes ──────────────────────────────────────────────────
function walkNodes(nodes, ctx) {
  if (!Array.isArray(nodes)) return '';
  return nodes
    .map(n => walkNode(n, ctx))
    .filter(Boolean)
    .join('\n');
}

// ── Dispatch table ────────────────────────────────────────────────────────
// Each handler receives (node, ctx) and returns a Python string.
const HANDLERS = {
  show:          handleShow,
  read:          handleRead,
  assign:        handleAssign,
  if:            handleIf,
  while:         handleWhile,
  for:           handleFor,
  loop:          handleLoop,
  break:         handleBreak,
  function_call: handleFunctionCall,
  empty:         () => '',   // placeholder lines produce nothing
};

function walkNode(node, ctx) {
  if (!node || !node.type) return '';
  const handler = HANDLERS[node.type];
  if (handler) return handler(node, ctx);
  // Unknown node — emit a visible comment so the user knows
  return `${pad(ctx)}# [nodo desconocido: ${node.type}]`;
}

// ── show → print(...) ─────────────────────────────────────────────────────
// data.parts: [{ type:'text', value:'...' } | { type:'variable', varId:'...' }]
//
// Single-part shorthand:   print("hola")   or   print(x)
// Multi-part:              print("Res: " + str(x))
function handleShow(node, ctx) {
  const parts = (node.data.parts || []).map(p => {
    if (p.type === 'text') return `"${escapePyStr(p.value)}"`;
    return resolveName(p.varId, ctx);  // variable reference
  });

  if (parts.length === 0) return `${pad(ctx)}print("")`;

  // When mixing text and variables Python needs str() on non-strings
  const needsCast = parts.length > 1;
  const args = needsCast
    ? parts.map((p, i) => {
        const isVar = node.data.parts[i].type === 'variable';
        const varType = isVar ? resolveType(node.data.parts[i].varId, ctx) : 'string';
        return (isVar && varType !== 'string') ? `str(${p})` : p;
      }).join(' + ')
    : parts[0];

  return `${pad(ctx)}print(${args})`;
}

// ── read → input() ────────────────────────────────────────────────────────
// data.targetVarId
// Wraps with float() or bool() cast based on variable type.
function handleRead(node, ctx) {
  const varId   = node.data.targetVarId;
  const varName = resolveName(varId, ctx);
  const varType = resolveType(varId, ctx);

  const castMap = { number: 'float', boolean: 'bool' };
  const cast    = castMap[varType];
  const expr    = cast ? `${cast}(input())` : `input()`;

  return `${pad(ctx)}${varName} = ${expr}`;
}

// ── assign → var op= expr ─────────────────────────────────────────────────
// data.targetVarId
// data.operator  ('=', '+=', '-=', '*=', '/=', '%=')
// data.expression: { type:'literal', valueType, value } | { type:'variable', varId }
function handleAssign(node, ctx) {
  const d       = node.data || {};
  const target  = resolveName(d.targetVarId, ctx);
  const op      = d.operator || '=';

  let rhs;
  if (!d.expression) {
    rhs = 'None';
  } else if (d.expression.type === 'variable') {
    rhs = resolveName(d.expression.varId, ctx);
  } else {
    // literal — value is already the correct JS type (number, boolean, string, [])
    rhs = pyLiteralFromValue(d.expression.valueType, d.expression.value);
  }

  return `${pad(ctx)}${target} ${op} ${rhs}`;
}

// ── if → if cond: / else: ────────────────────────────────────────────────
// data.condition: { leftVarId, operator, rightType:'literal'|'variable',
//                   rightValue (when literal), rightVarId (when variable) }
// children[]: flat list of then-body nodes (no else branch yet in the UI)
function handleIf(node, ctx) {
  const cond     = buildCondition(node.data.condition, ctx);
  const childCtx = { ...ctx, indent: ctx.indent + 1 };
  const body     = walkNodes(node.children || [], childCtx) || `${pad(childCtx)}pass`;

  return `${pad(ctx)}if ${cond}:\n${body}`;
}

// ── while → while cond: ───────────────────────────────────────────────────
// data.condition: same shape as if
function handleWhile(node, ctx) {
  const cond     = buildCondition(node.data.condition, ctx);
  const childCtx = { ...ctx, indent: ctx.indent + 1 };
  const body     = walkNodes(node.children || [], childCtx) || `${pad(childCtx)}pass`;

  return `${pad(ctx)}while ${cond}:\n${body}`;
}

// ── for → for i in range(N): / for x in lista: ───────────────────────────
// data.subType   : 'range' | 'iterable'
// data.iterName  : iterator variable name string (not an ID)
// data.end       : (range) end value
// data.iterableVarId : (iterable) variable ID
function handleFor(node, ctx) {
  const d        = node.data || {};
  const iterName = sanitizeName(d.iterName || 'i');
  const childCtx = { ...ctx, indent: ctx.indent + 1 };
  const body     = walkNodes(node.children || [], childCtx) || `${pad(childCtx)}pass`;

  let header;
  if (d.subType === 'iterable') {
    const collection = resolveName(d.iterableVarId, ctx);
    header = `for ${iterName} in ${collection}:`;
  } else {
    // range — start is always 0 in the current UI
    header = `for ${iterName} in range(${d.start ?? 0}, ${d.end ?? 0}):`;
  }

  return `${pad(ctx)}${header}\n${body}`;
}

// ── loop → while True: ────────────────────────────────────────────────────
function handleLoop(node, ctx) {
  const childCtx = { ...ctx, indent: ctx.indent + 1 };
  const body     = walkNodes(node.children || [], childCtx) || `${pad(childCtx)}pass`;
  return `${pad(ctx)}while True:\n${body}`;
}

// ── break ─────────────────────────────────────────────────────────────────
function handleBreak(node, ctx) {
  return `${pad(ctx)}break`;
}

// ── function_call → [target =] name(arg) ─────────────────────────────────
// data.funcName    : string name of the function
// data.argVarId    : variable ID to pass as argument (optional)
// data.targetVarId : variable ID to store return value in (optional)
function handleFunctionCall(node, ctx) {
  const d      = node.data || {};
  const name   = sanitizeName(d.funcName || 'func');
  const arg    = d.argVarId ? resolveName(d.argVarId, ctx) : '';
  const call   = `${name}(${arg})`;

  if (d.targetVarId) {
    return `${pad(ctx)}${resolveName(d.targetVarId, ctx)} = ${call}`;
  }
  return `${pad(ctx)}${call}`;
}

// ── Condition builder ─────────────────────────────────────────────────────
// condition: { leftVarId, leftType, operator,
//              rightType:'literal'|'variable', rightValue, rightVarId }
function buildCondition(cond, ctx) {
  if (!cond) return 'True';

  const left  = resolveName(cond.leftVarId, ctx);
  const op    = pyOperator(cond.operator || '==');

  let right;
  if (cond.rightType === 'variable') {
    right = resolveName(cond.rightVarId, ctx);
  } else {
    right = pyLiteralFromValue(cond.leftType, cond.rightValue);
  }

  return `${left} ${op} ${right}`;
}

// ── Helpers ───────────────────────────────────────────────────────────────

// Current indentation string
function pad(ctx) {
  return INDENT.repeat(ctx.indent);
}

// Resolve a variable ID to its Python name
function resolveName(id, ctx) {
  if (!id) return '_undefined_';
  const v = ctx.varMap[id];
  return v ? sanitizeName(v.name) : '_undefined_';
}

// Resolve a variable ID to its type string
function resolveType(id, ctx) {
  if (!id) return 'string';
  const v = ctx.varMap[id];
  return v ? v.type : 'string';
}

// Convert a JS value to a Python literal, given the CodeFlow type
function pyLiteralFromValue(type, value) {
  if (type === 'boolean') {
    return (value === true || value === 'true') ? 'True' : 'False';
  }
  if (type === 'number') {
    const n = Number(value);
    return isNaN(n) ? '0' : String(n);
  }
  if (type === 'list') return '[]';
  // string (and fallback)
  if (value === null || value === undefined) return '""';
  return `"${escapePyStr(String(value))}"`;
}

// Default Python value for a freshly declared variable
function pyDefaultValue(type, value) {
  return pyLiteralFromValue(type, value ?? null);
}

// Map CodeFlow/JS operators to Python equivalents
function pyOperator(op) {
  const map = {
    '=':  '==',   // assignment op used by mistake in condition context
    '==': '==',
    '!=': '!=',
    '<':  '<',
    '>':  '>',
    '<=': '<=',
    '>=': '>=',
  };
  return map[op] ?? op;
}

// Make a valid Python identifier from any string
function sanitizeName(name) {
  if (!name) return '_var';
  return name
    .replace(/[\s\-]/g, '_')
    .replace(/[^a-zA-Z0-9_]/g, '')
    .replace(/^(\d)/, '_$1') || '_var';
}

// Escape special characters inside Python double-quoted strings
function escapePyStr(str) {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/"/g,  '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}

module.exports = { transpile };
